import type { Calculator } from "./types"

export const financeCalculators: Calculator[] = [
  {
    slug: "loan-calculator",
    metaTitleKey: "finance.loan.metaTitle",
    metaDescriptionKey: "finance.loan.metaDescription",
    titleKey: "finance.loan.title",
    category: "Finance",
    descriptionKey: "finance.loan.desc",
    inputs: [
      { label: "finance.loan.principal", name: "principal", type: "number", unit: "$" },
      { label: "finance.loan.rate", name: "rate", type: "number", unit: "%" },
      { label: "finance.loan.years", name: "years", type: "number", unit: "years" },
    ],
    formulaId: "loan",
    sections: [
      { id: "intro", titleKey: "finance.loan.about", contentKey: "finance.loan.aboutText" },
      { id: "formula", titleKey: "finance.loan.formula", contentKey: "finance.loan.formulaText" },
    ],
    faqTitleKey: "finance.loan.faqTitle",
    faqs: [
      { qKey: "finance.loan.faq.0.q", aKey: "finance.loan.faq.0.a" },
      { qKey: "finance.loan.faq.1.q", aKey: "finance.loan.faq.1.a" },
      { qKey: "finance.loan.faq.2.q", aKey: "finance.loan.faq.2.a" },
      { qKey: "finance.loan.faq.3.q", aKey: "finance.loan.faq.3.a" },
      { qKey: "finance.loan.faq.4.q", aKey: "finance.loan.faq.4.a" },
      { qKey: "finance.loan.faq.5.q", aKey: "finance.loan.faq.5.a" },
    ],
  },
  {
    slug: "compound-interest-calculator",
    metaTitleKey: "finance.compound.metaTitle",
    metaDescriptionKey: "finance.compound.metaDescription",
    titleKey: "finance.compound.title",
    category: "Finance",
    descriptionKey: "finance.compound.desc",
    inputs: [
      { label: "finance.compound.principal", name: "principal", type: "number", unit: "$" },
      { label: "finance.compound.rate", name: "rate", type: "number", unit: "%" },
      { label: "finance.compound.years", name: "years", type: "number", unit: "years" },
      { label: "finance.compound.compounds", name: "compounds", type: "number", unit: "times/year" },
    ],
    formulaId: "compound",
    sections: [
      { id: "intro", titleKey: "finance.compound.about", contentKey: "finance.compound.aboutText" },
      { id: "formula", titleKey: "finance.compound.formula", contentKey: "finance.compound.formulaText" },
    ],
    faqTitleKey: "finance.compound.faqTitle",
    faqs: [
      { qKey: "finance.compound.faq.0.q", aKey: "finance.compound.faq.0.a" },
      { qKey: "finance.compound.faq.1.q", aKey: "finance.compound.faq.1.a" },
      { qKey: "finance.compound.faq.2.q", aKey: "finance.compound.faq.2.a" },
      { qKey: "finance.compound.faq.3.q", aKey: "finance.compound.faq.3.a" },
      { qKey: "finance.compound.faq.4.q", aKey: "finance.compound.faq.4.a" },
      { qKey: "finance.compound.faq.5.q", aKey: "finance.compound.faq.5.a" },
    ],
  },
  {
    slug: "savings-calculator",
    metaTitleKey: "finance.savings.metaTitle",
    metaDescriptionKey: "finance.savings.metaDescription",
    titleKey: "finance.savings.title",
    category: "Finance",
    descriptionKey: "finance.savings.desc",
    inputs: [
      { label: "finance.savings.initial", name: "initial", type: "number", unit: "$" },
      { label: "finance.savings.monthly", name: "monthly", type: "number", unit: "$" },
      { label: "finance.savings.rate", name: "rate", type: "number", unit: "%" },
      { label: "finance.savings.years", name: "years", type: "number", unit: "years" },
    ],
    formulaId: "savings",
    sections: [
      { id: "intro", titleKey: "finance.savings.about", contentKey: "finance.savings.aboutText" },
      { id: "formula", titleKey: "finance.savings.formula", contentKey: "finance.savings.formulaText" },
    ],
    faqTitleKey: "finance.savings.faqTitle",
    faqs: [
      { qKey: "finance.savings.faq.0.q", aKey: "finance.savings.faq.0.a" },
      { qKey: "finance.savings.faq.1.q", aKey: "finance.savings.faq.1.a" },
      { qKey: "finance.savings.faq.2.q", aKey: "finance.savings.faq.2.a" },
      { qKey: "finance.savings.faq.3.q", aKey: "finance.savings.faq.3.a" },
      { qKey: "finance.savings.faq.4.q", aKey: "finance.savings.faq.4.a" },
      { qKey: "finance.savings.faq.5.q", aKey: "finance.savings.faq.5.a" },
    ],
  },
  {
    slug: "mortgage-calculator",
    metaTitleKey: "finance.mortgage.metaTitle",
    metaDescriptionKey: "finance.mortgage.metaDescription",
    titleKey: "finance.mortgage.title",
    category: "Finance",
    descriptionKey: "finance.mortgage.desc",
    inputs: [
      { label: "finance.mortgage.homePrice", name: "homePrice", type: "number", unit: "$" },
      { label: "finance.mortgage.downPayment", name: "downPayment", type: "number", unit: "$" },
      { label: "finance.mortgage.rate", name: "rate", type: "number", unit: "%" },
      { label: "finance.mortgage.years", name: "years", type: "number", unit: "years" },
    ],
    formulaId: "mortgage",
    sections: [
      { id: "intro", titleKey: "finance.mortgage.about", contentKey: "finance.mortgage.aboutText" },
      { id: "formula", titleKey: "finance.mortgage.formula", contentKey: "finance.mortgage.formulaText" },
    ],
    faqTitleKey: "finance.mortgage.faqTitle",
    faqs: [
      { qKey: "finance.mortgage.faq.0.q", aKey: "finance.mortgage.faq.0.a" },
      { qKey: "finance.mortgage.faq.1.q", aKey: "finance.mortgage.faq.1.a" },
      { qKey: "finance.mortgage.faq.2.q", aKey: "finance.mortgage.faq.2.a" },
      { qKey: "finance.mortgage.faq.3.q", aKey: "finance.mortgage.faq.3.a" },
      { qKey: "finance.mortgage.faq.4.q", aKey: "finance.mortgage.faq.4.a" },
      { qKey: "finance.mortgage.faq.5.q", aKey: "finance.mortgage.faq.5.a" },
    ],
  },
  {
    slug: "roi-calculator",
    metaTitleKey: "finance.roi.metaTitle",
    metaDescriptionKey: "finance.roi.metaDescription",
    titleKey: "finance.roi.title",
    category: "Finance",
    descriptionKey: "finance.roi.desc",
    inputs: [
      { label: "finance.roi.investment", name: "investment", type: "number", unit: "$" },
      { label: "finance.roi.gain", name: "gain", type: "number", unit: "$" },
    ],
    formulaId: "roi",
    sections: [
      { id: "intro", titleKey: "finance.roi.about", contentKey: "finance.roi.aboutText" },
      { id: "formula", titleKey: "finance.roi.formula", contentKey: "finance.roi.formulaText" },
    ],
    faqTitleKey: "finance.roi.faqTitle",
    faqs: [
      { qKey: "finance.roi.faq.0.q", aKey: "finance.roi.faq.0.a" },
      { qKey: "finance.roi.faq.1.q", aKey: "finance.roi.faq.1.a" },
      { qKey: "finance.roi.faq.2.q", aKey: "finance.roi.faq.2.a" },
      { qKey: "finance.roi.faq.3.q", aKey: "finance.roi.faq.3.a" },
      { qKey: "finance.roi.faq.4.q", aKey: "finance.roi.faq.4.a" },
      { qKey: "finance.roi.faq.5.q", aKey: "finance.roi.faq.5.a" },
    ],
  },
  {
    slug: "breakeven-calculator",
    metaTitleKey: "finance.breakeven.metaTitle",
    metaDescriptionKey: "finance.breakeven.metaDescription",
    titleKey: "finance.breakeven.title",
    category: "Finance",
    descriptionKey: "finance.breakeven.desc",
    inputs: [
      { label: "finance.breakeven.fixedCosts", name: "fixedCosts", type: "number", unit: "$" },
      { label: "finance.breakeven.variableCost", name: "variableCost", type: "number", unit: "$" },
      { label: "finance.breakeven.price", name: "price", type: "number", unit: "$" },
    ],
    formulaId: "breakeven",
    sections: [
      { id: "intro", titleKey: "finance.breakeven.about", contentKey: "finance.breakeven.aboutText" },
      { id: "formula", titleKey: "finance.breakeven.formula", contentKey: "finance.breakeven.formulaText" },
    ],
    faqTitleKey: "finance.breakeven.faqTitle",
    faqs: [
      { qKey: "finance.breakeven.faq.0.q", aKey: "finance.breakeven.faq.0.a" },
      { qKey: "finance.breakeven.faq.1.q", aKey: "finance.breakeven.faq.1.a" },
      { qKey: "finance.breakeven.faq.2.q", aKey: "finance.breakeven.faq.2.a" },
      { qKey: "finance.breakeven.faq.3.q", aKey: "finance.breakeven.faq.3.a" },
      { qKey: "finance.breakeven.faq.4.q", aKey: "finance.breakeven.faq.4.a" },
      { qKey: "finance.breakeven.faq.5.q", aKey: "finance.breakeven.faq.5.a" },
    ],
  },
  {
    slug: "discount-calculator",
    metaTitleKey: "finance.discount.metaTitle",
    metaDescriptionKey: "finance.discount.metaDescription",
    titleKey: "finance.discount.title",
    category: "Finance",
    descriptionKey: "finance.discount.desc",
    inputs: [
      { label: "finance.discount.originalPrice", name: "originalPrice", type: "number", unit: "$" },
      { label: "finance.discount.discountPercent", name: "discountPercent", type: "number", unit: "%" },
    ],
    formulaId: "discount",
    sections: [
      { id: "intro", titleKey: "finance.discount.about", contentKey: "finance.discount.aboutText" },
      { id: "formula", titleKey: "finance.discount.formula", contentKey: "finance.discount.formulaText" },
    ],
    faqTitleKey: "finance.discount.faqTitle",
    faqs: [
      { qKey: "finance.discount.faq.0.q", aKey: "finance.discount.faq.0.a" },
      { qKey: "finance.discount.faq.1.q", aKey: "finance.discount.faq.1.a" },
      { qKey: "finance.discount.faq.2.q", aKey: "finance.discount.faq.2.a" },
      { qKey: "finance.discount.faq.3.q", aKey: "finance.discount.faq.3.a" },
      { qKey: "finance.discount.faq.4.q", aKey: "finance.discount.faq.4.a" },
      { qKey: "finance.discount.faq.5.q", aKey: "finance.discount.faq.5.a" },
    ],
  },
  {
    slug: "tip-calculator",
    metaTitleKey: "finance.tip.metaTitle",
    metaDescriptionKey: "finance.tip.metaDescription",
    titleKey: "finance.tip.title",
    category: "Finance",
    descriptionKey: "finance.tip.desc",
    inputs: [
      { label: "finance.tip.billAmount", name: "billAmount", type: "number", unit: "$" },
      { label: "finance.tip.tipPercent", name: "tipPercent", type: "number", unit: "%" },
      { label: "finance.tip.people", name: "people", type: "number", unit: "people" },
    ],
    formulaId: "tip",
    sections: [
      { id: "intro", titleKey: "finance.tip.about", contentKey: "finance.tip.aboutText" },
      { id: "formula", titleKey: "finance.tip.formula", contentKey: "finance.tip.formulaText" },
    ],
    faqTitleKey: "finance.tip.faqTitle",
    faqs: [
      { qKey: "finance.tip.faq.0.q", aKey: "finance.tip.faq.0.a" },
      { qKey: "finance.tip.faq.1.q", aKey: "finance.tip.faq.1.a" },
      { qKey: "finance.tip.faq.2.q", aKey: "finance.tip.faq.2.a" },
      { qKey: "finance.tip.faq.3.q", aKey: "finance.tip.faq.3.a" },
      { qKey: "finance.tip.faq.4.q", aKey: "finance.tip.faq.4.a" },
      { qKey: "finance.tip.faq.5.q", aKey: "finance.tip.faq.5.a" },
    ],
  },
  {
    slug: "inflation-calculator",
    metaTitleKey: "finance.inflation.metaTitle",
    metaDescriptionKey: "finance.inflation.metaDescription",
    titleKey: "finance.inflation.title",
    category: "Finance",
    descriptionKey: "finance.inflation.desc",
    inputs: [
      { label: "finance.inflation.amount", name: "amount", type: "number", unit: "$" },
      { label: "finance.inflation.years", name: "years", type: "number", unit: "years" },
      { label: "finance.inflation.rate", name: "rate", type: "number", unit: "%" },
    ],
    formulaId: "inflation",
    sections: [
      { id: "intro", titleKey: "finance.inflation.about", contentKey: "finance.inflation.aboutText" },
      { id: "formula", titleKey: "finance.inflation.formula", contentKey: "finance.inflation.formulaText" },
    ],
    faqTitleKey: "finance.inflation.faqTitle",
    faqs: [
      { qKey: "finance.inflation.faq.0.q", aKey: "finance.inflation.faq.0.a" },
      { qKey: "finance.inflation.faq.1.q", aKey: "finance.inflation.faq.1.a" },
      { qKey: "finance.inflation.faq.2.q", aKey: "finance.inflation.faq.2.a" },
      { qKey: "finance.inflation.faq.3.q", aKey: "finance.inflation.faq.3.a" },
      { qKey: "finance.inflation.faq.4.q", aKey: "finance.inflation.faq.4.a" },
      { qKey: "finance.inflation.faq.5.q", aKey: "finance.inflation.faq.5.a" },
    ],
  },
  {
    slug: "currency-converter",
    metaTitleKey: "finance.currency.metaTitle",
    metaDescriptionKey: "finance.currency.metaDescription",
    titleKey: "finance.currency.title",
    category: "Finance",
    descriptionKey: "finance.currency.desc",
    inputs: [
      { label: "finance.currency.amount", name: "amount", type: "number", unit: "amount" },
      { label: "finance.currency.fromCurrency", name: "fromCurrency", type: "text" },
      { label: "finance.currency.toCurrency", name: "toCurrency", type: "text" },
    ],
    formulaId: "currency",
    sections: [
      { id: "intro", titleKey: "finance.currency.about", contentKey: "finance.currency.aboutText" },
      { id: "formula", titleKey: "finance.currency.formula", contentKey: "finance.currency.formulaText" },
    ],
    faqTitleKey: "finance.currency.faqTitle",
    faqs: [
      { qKey: "finance.currency.faq.0.q", aKey: "finance.currency.faq.0.a" },
      { qKey: "finance.currency.faq.1.q", aKey: "finance.currency.faq.1.a" },
      { qKey: "finance.currency.faq.2.q", aKey: "finance.currency.faq.2.a" },
      { qKey: "finance.currency.faq.3.q", aKey: "finance.currency.faq.3.a" },
      { qKey: "finance.currency.faq.4.q", aKey: "finance.currency.faq.4.a" },
      { qKey: "finance.currency.faq.5.q", aKey: "finance.currency.faq.5.a" },
    ],
  },
]