import type { Calculator } from "./types"

export const healthCalculators: Calculator[] = [
  {
    slug: "body-fat-calculator",
    metaTitleKey: "health.bodyFat.title",
    metaDescriptionKey: "health.bodyFat.desc",
    titleKey: "health.bodyFat.title",
    category: "Health",
    descriptionKey: "health.bodyFat.desc",
    formulaId: "body-fat",

    inputs: [
      {
        label: "health.bodyFat.gender", name: "gender", type: "select", options: [
          { value: "male", label: "health.bodyFat.male" },
          { value: "female", label: "health.bodyFat.female" },
        ]
      },
      { label: "health.bodyFat.waist", name: "waist", type: "number", unit: "cm" },
      { label: "health.bodyFat.neck", name: "neck", type: "number", unit: "cm" },
      { label: "health.bodyFat.hip", name: "hip", type: "number", unit: "cm" },
      { label: "health.bodyFat.height", name: "height", type: "number", unit: "cm" },
    ],
    toc: [
      { id: "about", labelKey: "health.bodyFat.tocAbout" },
      { id: "formula", labelKey: "health.bodyFat.tocFormula" },
      { id: "navy-method", labelKey: "health.bodyFat.tocnavymethod" },
      { id: "bmi-method", labelKey: "health.bodyFat.tocbmimethod" },
      { id: "interpretation", labelKey: "health.bodyFat.tocinterpretation" },
      { id: "faqs", labelKey: "health.bodyFat.tocFaqs" },
    ],
    heading:"health.bodyFat.heading",
    sections: [
      {
        id: "about",
        titleKey: "health.bodyFat.about",
        titleKey2: "health.bodyFat.abouttitle",
        contentKey: "health.bodyFat.aboutText",
      },
      {
        id: "formula",
        titleKey: "health.bodyFat.formula",
        titleKey2: "health.bodyFat.formulatitle",
        subsections: [
          {
            id: "formula-overview",
            contentKey: "health.bodyFat.formulaText",
          },
          {
            id: "navy-method",
            titleKey: "health.bodyFat.navyMethodTitle",
            contentKey: "health.bodyFat.navyMethodText",
            subsections: [
              { id: "navy-men", contentKey: "health.bodyFat.navyMethodMen" },
              { id: "navy-women", contentKey: "health.bodyFat.navyMethodWomen" },
              { id: "navy-note", contentKey: "health.bodyFat.navyMethodNote" },
            ],
          },
          {
            id: "bmi-method",
            titleKey: "health.bodyFat.bmiMethodTitle",
            contentKey: "health.bodyFat.bmiMethodText",
            subsections: [
              { id: "bmi-simplified", contentKey: "health.bodyFat.bmiSimplifiedText" },
            ],
          },
          {
            id: "interpretation",
            titleKey: "health.bodyFat.interpretationTitle",
            contentKey: "health.bodyFat.interpretationText",
          },
        ],
      },
    ],

    faqTitleKey: "health.bodyFat.faqTitle",
    faqs: [
      { qKey: "health.bodyFat.faq.0.q", aKey: "health.bodyFat.faq.0.a" },
      { qKey: "health.bodyFat.faq.1.q", aKey: "health.bodyFat.faq.1.a" },
      { qKey: "health.bodyFat.faq.2.q", aKey: "health.bodyFat.faq.2.a" },
      { qKey: "health.bodyFat.faq.3.q", aKey: "health.bodyFat.faq.3.a" },
      { qKey: "health.bodyFat.faq.4.q", aKey: "health.bodyFat.faq.4.a" },
      { qKey: "health.bodyFat.faq.5.q", aKey: "health.bodyFat.faq.5.a" },
    ],
  },

{
  slug: "bmi-calculator",
  metaTitleKey: "health.bmi.title",
  metaDescriptionKey: "health.bmi.desc",
  titleKey: "health.bmi.title",
  category: "Health",
  descriptionKey: "health.bmi.desc",
  formulaId: "bmi",

  toc: [
    { id: "why-use", labelKey: "health.bmi.tocwhy" },
    { id: "how-works", labelKey: "health.bmi.tochowitworks" },
    { id: "why-matters", labelKey: "health.bmi.tocwhybmi" },
    { id: "understanding", labelKey: "health.bmi.tocUnderstanding" },
    { id: "examples", labelKey: "health.bmi.tocexample" },
    { id: "categories", labelKey: "health.bmi.toccategories" },

  ],

  inputs: [
    { label: "health.bmi.weight", name: "weight", type: "number", unit: "kg" },
    { label: "health.bmi.height", name: "height", type: "number", unit: "cm" },
  ],

  heading: "health.bmi.heading",

  sections: [
    {
      id: "about",
      titleKey: "health.bmi.section1Title",
      contentKey: "health.bmi.section1Content",
      subsections: [
        {
          id: "why-use",
          titleKey: "health.bmi.section1Sub1Title",
          introKey: "health.bmi.section1Sub1Intro",
          contentKey: "health.bmi.section1Sub1Text",
          listKey: "health.bmi.section1Sub1List",
          endKey: "health.bmi.section1Sub1End",
        },
        {
          id: "how-works",
          titleKey: "health.bmi.section1Sub2Title",
          introKey: "health.bmi.section1Sub2Intro",
          listKey: "health.bmi.section1Sub2List",
          contentKey: "health.bmi.section1Sub2Text",
          endKey: "health.bmi.section1Sub2End",
        },
        {
          id: "why-matters",
          titleKey: "health.bmi.section1Sub3Title",
          contentKey: "health.bmi.section1Sub3Intro",
          endKey: "health.bmi.section1Sub3End",
        },
      ],
    },
    {
      id: "formula",
      titleKey: "health.bmi.section2Title",
      introKey: "health.bmi.section2Intro",
      contentKey: "health.bmi.section2Text",
      subsections: [
        {
          id: "metric-formula",
          contentKey: "health.bmi.section2MetricFormula",
          type: "formula",
        },
        {
          id: "imperial-formula",
          introKey: "health.bmi.section2ImperialIntro",
          contentKey: "health.bmi.section2ImperialFormula",
          type: "formula",
        },
        {
          id: "formula-end",
          contentKey: "health.bmi.section2End",
        },
        {
          id: "understanding",
          titleKey: "health.bmi.section2Sub1Title",
          imageKey: "health.bmi.section2Sub1Image",
          imageAltKey: "health.bmi.section2Sub1ImageAlt",
          contentKey: "health.bmi.section2Sub1Intro",
          textKey: "health.bmi.section2Sub1Text",
          pointsKey: "health.bmi.section2Sub1Points",
        },
        {
          id: "examples",
          titleKey: "health.bmi.section2Sub2Title",
          introKey: "health.bmi.section2Sub2Intro",
          subsections: [
            {
              id: "metric-example",
              labelKey: "health.bmi.section2Sub2MetricLabel",
              contentKey: "health.bmi.section2Sub2MetricText",
              formulaKey: "health.bmi.section2Sub2MetricFormula",
              resultKey: "health.bmi.section2Sub2MetricResult",
            },
            {
              id: "imperial-example",
              labelKey: "health.bmi.section2Sub2ImperialLabel",
              contentKey: "health.bmi.section2Sub2ImperialText",
              formulaKey: "health.bmi.section2Sub2ImperialFormula",
              resultKey: "health.bmi.section2Sub2ImperialResult",
            },
          ],
        },
        {
          id: "categories",
          titleKey: "health.bmi.section2Sub3Title",
          contentKey: "health.bmi.section2Sub3Intro",
          imageKey: "health.bmi.section2Sub3Image",
          imageAltKey: "health.bmi.section2Sub3ImageAlt",
          endKey: "health.bmi.section2Sub3End1",
          end2Key: "health.bmi.section2Sub3End2",
        },
      ],
    },
  ],

  faqTitleKey: "health.bmi.faqTitle",
  faqs: [
    { qKey: "health.bmi.faq.0.q", aKey: "health.bmi.faq.0.a" },
    { qKey: "health.bmi.faq.1.q", aKey: "health.bmi.faq.1.a" },
    { qKey: "health.bmi.faq.2.q", aKey: "health.bmi.faq.2.a" },
    { qKey: "health.bmi.faq.3.q", aKey: "health.bmi.faq.3.a" },
    { qKey: "health.bmi.faq.4.q", aKey: "health.bmi.faq.4.a" },
    { qKey: "health.bmi.faq.5.q", aKey: "health.bmi.faq.5.a" },
  ],
},
  {
    slug: "calorie-calculator",
    metaTitleKey: "health.calories.metaTitle",
    metaDescriptionKey: "health.calories.metaDescription",
    titleKey: "health.calories.title",
    category: "Health",
    descriptionKey: "health.calories.desc",
    inputs: [
      { label: "health.calories.age", name: "age", type: "number", unit: "years" },
      { label: "health.calories.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.calories.height", name: "height", type: "number", unit: "cm" },
      {
        label: "health.calories.activity",
        name: "activity",
        type: "select",
        options: [
          { value: "1.2", label: "health.calories.sedentary" },
          { value: "1.375", label: "health.calories.light" },
          { value: "1.55", label: "health.calories.moderate" },
          { value: "1.725", label: "health.calories.active" },
        ],
      },
    ],
    formulaId: "calories",
    sections: [
      { id: "intro", titleKey: "health.calories.about", contentKey: "health.calories.aboutText" },
      { id: "formula", titleKey: "health.calories.formula", contentKey: "health.calories.formulaText" },
    ],
    faqTitleKey: "health.calories.faqTitle",
    faqs: [
      { qKey: "health.calories.faq.0.q", aKey: "health.calories.faq.0.a" },
      { qKey: "health.calories.faq.1.q", aKey: "health.calories.faq.1.a" },
      { qKey: "health.calories.faq.2.q", aKey: "health.calories.faq.2.a" },
      { qKey: "health.calories.faq.3.q", aKey: "health.calories.faq.3.a" },
      { qKey: "health.calories.faq.4.q", aKey: "health.calories.faq.4.a" },
      { qKey: "health.calories.faq.5.q", aKey: "health.calories.faq.5.a" },
    ],
  },
  {
    slug: "water-intake-calculator",
    metaTitleKey: "health.waterIntake.metaTitle",
    metaDescriptionKey: "health.waterIntake.metaDescription",
    titleKey: "health.waterIntake.title",
    category: "Health",
    descriptionKey: "health.waterIntake.desc",
    inputs: [
      { label: "health.waterIntake.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.waterIntake.activity", name: "activity", type: "number", unit: "0-2" },
    ],
    formulaId: "water",
    sections: [
      { id: "intro", titleKey: "health.waterIntake.about", contentKey: "health.waterIntake.aboutText" },
      { id: "formula", titleKey: "health.waterIntake.formula", contentKey: "health.waterIntake.formulaText" },
    ],
    faqTitleKey: "health.waterIntake.faqTitle",
    faqs: [
      { qKey: "health.waterIntake.faq.0.q", aKey: "health.waterIntake.faq.0.a" },
      { qKey: "health.waterIntake.faq.1.q", aKey: "health.waterIntake.faq.1.a" },
      { qKey: "health.waterIntake.faq.2.q", aKey: "health.waterIntake.faq.2.a" },
      { qKey: "health.waterIntake.faq.3.q", aKey: "health.waterIntake.faq.3.a" },
      { qKey: "health.waterIntake.faq.4.q", aKey: "health.waterIntake.faq.4.a" },
      { qKey: "health.waterIntake.faq.5.q", aKey: "health.waterIntake.faq.5.a" },
    ],
  },
  {
    slug: "running-pace-calculator",
    metaTitleKey: "health.pace.metaTitle",
    metaDescriptionKey: "health.pace.metaDescription",
    titleKey: "health.pace.title",
    category: "Health",
    descriptionKey: "health.pace.desc",
    inputs: [
      { label: "health.pace.distance", name: "distance", type: "number", unit: "km" },
      { label: "health.pace.time", name: "time", type: "number", unit: "minutes" },
    ],
    formulaId: "pace",
    sections: [
      { id: "intro", titleKey: "health.pace.about", contentKey: "health.pace.aboutText" },
      { id: "formula", titleKey: "health.pace.formula", contentKey: "health.pace.formulaText" },
    ],
    faqTitleKey: "health.pace.faqTitle",
    faqs: [
      { qKey: "health.pace.faq.0.q", aKey: "health.pace.faq.0.a" },
      { qKey: "health.pace.faq.1.q", aKey: "health.pace.faq.1.a" },
      { qKey: "health.pace.faq.2.q", aKey: "health.pace.faq.2.a" },
      { qKey: "health.pace.faq.3.q", aKey: "health.pace.faq.3.a" },
      { qKey: "health.pace.faq.4.q", aKey: "health.pace.faq.4.a" },
      { qKey: "health.pace.faq.5.q", aKey: "health.pace.faq.5.a" },
    ],
  },
  {
    slug: "heart-rate-calculator",
    metaTitleKey: "health.heartRate.metaTitle",
    metaDescriptionKey: "health.heartRate.metaDescription",
    titleKey: "health.heartRate.title",
    category: "Health",
    descriptionKey: "health.heartRate.desc",
    inputs: [
      { label: "health.heartRate.age", name: "age", type: "number", unit: "years" },
      { label: "health.heartRate.restingHR", name: "restingHR", type: "number", unit: "bpm" },
    ],
    formulaId: "heart-rate",
    sections: [
      { id: "intro", titleKey: "health.heartRate.about", contentKey: "health.heartRate.aboutText" },
      { id: "formula", titleKey: "health.heartRate.formula", contentKey: "health.heartRate.formulaText" },
    ],
    faqTitleKey: "health.heartRate.faqTitle",
    faqs: [
      { qKey: "health.heartRate.faq.0.q", aKey: "health.heartRate.faq.0.a" },
      { qKey: "health.heartRate.faq.1.q", aKey: "health.heartRate.faq.1.a" },
      { qKey: "health.heartRate.faq.2.q", aKey: "health.heartRate.faq.2.a" },
      { qKey: "health.heartRate.faq.3.q", aKey: "health.heartRate.faq.3.a" },
      { qKey: "health.heartRate.faq.4.q", aKey: "health.heartRate.faq.4.a" },
      { qKey: "health.heartRate.faq.5.q", aKey: "health.heartRate.faq.5.a" },
    ],
  },
  {
    slug: "protein-calculator",
    metaTitleKey: "health.protein.metaTitle",
    metaDescriptionKey: "health.protein.metaDescription",
    titleKey: "health.protein.title",
    category: "Health",
    descriptionKey: "health.protein.desc",
    inputs: [
      { label: "health.protein.weight", name: "weight", type: "number", unit: "kg" },
      {
        label: "health.protein.goal",
        name: "goal",
        type: "select",
        options: [
          { value: "0.8", label: "health.protein.maintenance" },
          { value: "1.9", label: "health.protein.muscle" },
          { value: "1.4", label: "health.protein.loss" },
        ],
      },
    ],
    formulaId: "protein",
    sections: [
      { id: "intro", titleKey: "health.protein.about", contentKey: "health.protein.aboutText" },
      { id: "formula", titleKey: "health.protein.formula", contentKey: "health.protein.formulaText" },
    ],
    faqTitleKey: "health.protein.faqTitle",
    faqs: [
      { qKey: "health.protein.faq.0.q", aKey: "health.protein.faq.0.a" },
      { qKey: "health.protein.faq.1.q", aKey: "health.protein.faq.1.a" },
      { qKey: "health.protein.faq.2.q", aKey: "health.protein.faq.2.a" },
      { qKey: "health.protein.faq.3.q", aKey: "health.protein.faq.3.a" },
      { qKey: "health.protein.faq.4.q", aKey: "health.protein.faq.4.a" },
      { qKey: "health.protein.faq.5.q", aKey: "health.protein.faq.5.a" },
    ],
  },
  {
    slug: "tdee-calculator",
    metaTitleKey: "health.tdee.metaTitle",
    metaDescriptionKey: "health.tdee.metaDescription",
    titleKey: "health.tdee.title",
    category: "Health",
    descriptionKey: "health.tdee.desc",
    inputs: [
      { label: "health.tdee.age", name: "age", type: "number", unit: "years" },
      { label: "health.tdee.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.tdee.height", name: "height", type: "number", unit: "cm" },
      {
        label: "health.tdee.activity",
        name: "activity",
        type: "select",
        options: [
          { value: "1.2", label: "health.tdee.sedentary" },
          { value: "1.375", label: "health.tdee.light" },
          { value: "1.55", label: "health.tdee.moderate" },
          { value: "1.725", label: "health.tdee.active" },
        ],
      },
    ],
    formulaId: "tdee",
    sections: [
      { id: "intro", titleKey: "health.tdee.about", contentKey: "health.tdee.aboutText" },
      { id: "formula", titleKey: "health.tdee.formula", contentKey: "health.tdee.formulaText" },
    ],
    faqTitleKey: "health.tdee.faqTitle",
    faqs: [
      { qKey: "health.tdee.faq.0.q", aKey: "health.tdee.faq.0.a" },
      { qKey: "health.tdee.faq.1.q", aKey: "health.tdee.faq.1.a" },
      { qKey: "health.tdee.faq.2.q", aKey: "health.tdee.faq.2.a" },
      { qKey: "health.tdee.faq.3.q", aKey: "health.tdee.faq.3.a" },
      { qKey: "health.tdee.faq.4.q", aKey: "health.tdee.faq.4.a" },
      { qKey: "health.tdee.faq.5.q", aKey: "health.tdee.faq.5.a" },
    ],
  },
  {
    slug: "macro-calculator",
    metaTitleKey: "health.macros.metaTitle",
    metaDescriptionKey: "health.macros.metaDescription",
    titleKey: "health.macros.title",
    category: "Health",
    descriptionKey: "health.macros.desc",
    inputs: [
      { label: "health.macros.calories", name: "calories", type: "number", unit: "kcal" },
      {
        label: "health.macros.diet",
        name: "diet",
        type: "select",
        options: [
          { value: "balanced", label: "health.macros.balanced" },
          { value: "lowcarb", label: "health.macros.lowCarb" },
          { value: "highprotein", label: "health.macros.highProtein" },
        ],
      },
    ],
    formulaId: "macros",
    sections: [
      { id: "intro", titleKey: "health.macros.about", contentKey: "health.macros.aboutText" },
      { id: "formula", titleKey: "health.macros.formula", contentKey: "health.macros.formulaText" },
    ],
    faqTitleKey: "health.macros.faqTitle",
    faqs: [
      { qKey: "health.macros.faq.0.q", aKey: "health.macros.faq.0.a" },
      { qKey: "health.macros.faq.1.q", aKey: "health.macros.faq.1.a" },
      { qKey: "health.macros.faq.2.q", aKey: "health.macros.faq.2.a" },
      { qKey: "health.macros.faq.3.q", aKey: "health.macros.faq.3.a" },
      { qKey: "health.macros.faq.4.q", aKey: "health.macros.faq.4.a" },
      { qKey: "health.macros.faq.5.q", aKey: "health.macros.faq.5.a" },
    ],
  },
  {
    slug: "body-fat-percentage",
    metaTitleKey: "health.bfp.metaTitle",
    metaDescriptionKey: "health.bfp.metaDescription",
    titleKey: "health.bfp.title",
    category: "Health",
    descriptionKey: "health.bfp.desc",
    inputs: [
      { label: "health.bfp.waist", name: "waist", type: "number", unit: "cm" },
      { label: "health.bfp.hip", name: "hip", type: "number", unit: "cm" },
      { label: "health.bfp.neck", name: "neck", type: "number", unit: "cm" },
    ],
    formulaId: "bfp",
    sections: [
      { id: "intro", titleKey: "health.bfp.about", contentKey: "health.bfp.aboutText" },
      { id: "formula", titleKey: "health.bfp.formula", contentKey: "health.bfp.formulaText" },
    ],
    faqTitleKey: "health.bfp.faqTitle",
    faqs: [
      { qKey: "health.bfp.faq.0.q", aKey: "health.bfp.faq.0.a" },
      { qKey: "health.bfp.faq.1.q", aKey: "health.bfp.faq.1.a" },
      { qKey: "health.bfp.faq.2.q", aKey: "health.bfp.faq.2.a" },
      { qKey: "health.bfp.faq.3.q", aKey: "health.bfp.faq.3.a" },
      { qKey: "health.bfp.faq.4.q", aKey: "health.bfp.faq.4.a" },
      { qKey: "health.bfp.faq.5.q", aKey: "health.bfp.faq.5.a" },
    ],
  },
]