import type { Calculator } from "./types"

export const healthCalculators: Calculator[] = [
  {
    slug: "body-fat-calculator",
    metaTitleKey: "health.bodyFat.metaTitle",
    metaDescriptionKey: "health.bodyFat.metaDescription",
    titleKey: "health.bodyFat.title",
    category: "Health",
    descriptionKey: "health.bodyFat.desc",
    inputs: [
      { label: "health.bodyFat.waist", name: "waist", type: "number", unit: "cm" },
      { label: "health.bodyFat.neck", name: "neck", type: "number", unit: "cm" },
      { label: "health.bodyFat.height", name: "height", type: "number", unit: "cm" },
      {
        label: "health.bodyFat.gender",
        name: "gender",
        type: "select",
        options: [
          { value: "male", label: "health.bodyFat.male" },
          { value: "female", label: "health.bodyFat.female" },
        ],
      },
    ],
    formulaId: "body-fat",
    sections: [
      { id: "intro", titleKey: "health.bodyFat.about", contentKey: "health.bodyFat.aboutText" },
      { id: "formula", titleKey: "health.bodyFat.formula", contentKey: "health.bodyFat.formulaText" },
    ],
    faqTitleKey: "health.bodyFat.faqTitle",
    faqs: [
      { qKey: "health.bodyFat.faq.0.q", aKey: "health.bodyFat.faq.0.a" },
      { qKey: "health.bodyFat.faq.1.q", aKey: "health.bodyFat.faq.1.a" },
      { qKey: "health.bodyFat.faq.2.q", aKey: "health.bodyFat.faq.2.a" },
      { qKey: "health.bodyFat.faq.3.q", aKey: "health.bodyFat.faq.3.a" },
      { qKey: "health.bodyFat.faq.4.q", aKey: "health.bodyFat.faq.4.a" },
      { qKey: "health.bodyFat.faq.5.q", aKey: "health.bodyFat.faq.5.a" },
    ],
  },
  {
    slug: "bmi-calculator",
    metaTitleKey: "health.bmi.metaTitle",
    metaDescriptionKey: "health.bmi.metaDescription",
    titleKey: "health.bmi.title",
    category: "Health",
    descriptionKey: "health.bmi.desc",
    inputs: [
      { label: "health.bmi.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.bmi.height", name: "height", type: "number", unit: "cm" },
    ],
    formulaId: "bmi",
    sections: [
      { id: "intro", titleKey: "health.bmi.about", contentKey: "health.bmi.aboutText" },
      { id: "formula", titleKey: "health.bmi.formula", contentKey: "health.bmi.formulaText" },
    ],
    faqTitleKey: "health.bmi.faqTitle",
    faqs: [
      { qKey: "health.bmi.faq.0.q", aKey: "health.bmi.faq.0.a" },
      { qKey: "health.bmi.faq.1.q", aKey: "health.bmi.faq.1.a" },
      { qKey: "health.bmi.faq.2.q", aKey: "health.bmi.faq.2.a" },
      { qKey: "health.bmi.faq.3.q", aKey: "health.bmi.faq.3.a" },
      { qKey: "health.bmi.faq.4.q", aKey: "health.bmi.faq.4.a" },
      { qKey: "health.bmi.faq.5.q", aKey: "health.bmi.faq.5.a" },
    ],
  },
  {
    slug: "calorie-calculator",
    metaTitleKey: "health.calories.metaTitle",
    metaDescriptionKey: "health.calories.metaDescription",
    titleKey: "health.calories.title",
    category: "Health",
    descriptionKey: "health.calories.desc",
    inputs: [
      { label: "health.calories.age", name: "age", type: "number", unit: "years" },
      { label: "health.calories.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.calories.height", name: "height", type: "number", unit: "cm" },
      {
        label: "health.calories.activity",
        name: "activity",
        type: "select",
        options: [
          { value: "1.2", label: "health.calories.sedentary" },
          { value: "1.375", label: "health.calories.light" },
          { value: "1.55", label: "health.calories.moderate" },
          { value: "1.725", label: "health.calories.active" },
        ],
      },
    ],
    formulaId: "calories",
    sections: [
      { id: "intro", titleKey: "health.calories.about", contentKey: "health.calories.aboutText" },
      { id: "formula", titleKey: "health.calories.formula", contentKey: "health.calories.formulaText" },
    ],
    faqTitleKey: "health.calories.faqTitle",
    faqs: [
      { qKey: "health.calories.faq.0.q", aKey: "health.calories.faq.0.a" },
      { qKey: "health.calories.faq.1.q", aKey: "health.calories.faq.1.a" },
      { qKey: "health.calories.faq.2.q", aKey: "health.calories.faq.2.a" },
      { qKey: "health.calories.faq.3.q", aKey: "health.calories.faq.3.a" },
      { qKey: "health.calories.faq.4.q", aKey: "health.calories.faq.4.a" },
      { qKey: "health.calories.faq.5.q", aKey: "health.calories.faq.5.a" },
    ],
  },
  {
    slug: "water-intake-calculator",
    metaTitleKey: "health.waterIntake.metaTitle",
    metaDescriptionKey: "health.waterIntake.metaDescription",
    titleKey: "health.waterIntake.title",
    category: "Health",
    descriptionKey: "health.waterIntake.desc",
    inputs: [
      { label: "health.waterIntake.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.waterIntake.activity", name: "activity", type: "number", unit: "0-2" },
    ],
    formulaId: "water",
    sections: [
      { id: "intro", titleKey: "health.waterIntake.about", contentKey: "health.waterIntake.aboutText" },
      { id: "formula", titleKey: "health.waterIntake.formula", contentKey: "health.waterIntake.formulaText" },
    ],
    faqTitleKey: "health.waterIntake.faqTitle",
    faqs: [
      { qKey: "health.waterIntake.faq.0.q", aKey: "health.waterIntake.faq.0.a" },
      { qKey: "health.waterIntake.faq.1.q", aKey: "health.waterIntake.faq.1.a" },
      { qKey: "health.waterIntake.faq.2.q", aKey: "health.waterIntake.faq.2.a" },
      { qKey: "health.waterIntake.faq.3.q", aKey: "health.waterIntake.faq.3.a" },
      { qKey: "health.waterIntake.faq.4.q", aKey: "health.waterIntake.faq.4.a" },
      { qKey: "health.waterIntake.faq.5.q", aKey: "health.waterIntake.faq.5.a" },
    ],
  },
  {
    slug: "running-pace-calculator",
    metaTitleKey: "health.pace.metaTitle",
    metaDescriptionKey: "health.pace.metaDescription",
    titleKey: "health.pace.title",
    category: "Health",
    descriptionKey: "health.pace.desc",
    inputs: [
      { label: "health.pace.distance", name: "distance", type: "number", unit: "km" },
      { label: "health.pace.time", name: "time", type: "number", unit: "minutes" },
    ],
    formulaId: "pace",
    sections: [
      { id: "intro", titleKey: "health.pace.about", contentKey: "health.pace.aboutText" },
      { id: "formula", titleKey: "health.pace.formula", contentKey: "health.pace.formulaText" },
    ],
    faqTitleKey: "health.pace.faqTitle",
    faqs: [
      { qKey: "health.pace.faq.0.q", aKey: "health.pace.faq.0.a" },
      { qKey: "health.pace.faq.1.q", aKey: "health.pace.faq.1.a" },
      { qKey: "health.pace.faq.2.q", aKey: "health.pace.faq.2.a" },
      { qKey: "health.pace.faq.3.q", aKey: "health.pace.faq.3.a" },
      { qKey: "health.pace.faq.4.q", aKey: "health.pace.faq.4.a" },
      { qKey: "health.pace.faq.5.q", aKey: "health.pace.faq.5.a" },
    ],
  },
  {
    slug: "heart-rate-calculator",
    metaTitleKey: "health.heartRate.metaTitle",
    metaDescriptionKey: "health.heartRate.metaDescription",
    titleKey: "health.heartRate.title",
    category: "Health",
    descriptionKey: "health.heartRate.desc",
    inputs: [
      { label: "health.heartRate.age", name: "age", type: "number", unit: "years" },
      { label: "health.heartRate.restingHR", name: "restingHR", type: "number", unit: "bpm" },
    ],
    formulaId: "heart-rate",
    sections: [
      { id: "intro", titleKey: "health.heartRate.about", contentKey: "health.heartRate.aboutText" },
      { id: "formula", titleKey: "health.heartRate.formula", contentKey: "health.heartRate.formulaText" },
    ],
    faqTitleKey: "health.heartRate.faqTitle",
    faqs: [
      { qKey: "health.heartRate.faq.0.q", aKey: "health.heartRate.faq.0.a" },
      { qKey: "health.heartRate.faq.1.q", aKey: "health.heartRate.faq.1.a" },
      { qKey: "health.heartRate.faq.2.q", aKey: "health.heartRate.faq.2.a" },
      { qKey: "health.heartRate.faq.3.q", aKey: "health.heartRate.faq.3.a" },
      { qKey: "health.heartRate.faq.4.q", aKey: "health.heartRate.faq.4.a" },
      { qKey: "health.heartRate.faq.5.q", aKey: "health.heartRate.faq.5.a" },
    ],
  },
  {
    slug: "protein-calculator",
    metaTitleKey: "health.protein.metaTitle",
    metaDescriptionKey: "health.protein.metaDescription",
    titleKey: "health.protein.title",
    category: "Health",
    descriptionKey: "health.protein.desc",
    inputs: [
      { label: "health.protein.weight", name: "weight", type: "number", unit: "kg" },
      {
        label: "health.protein.goal",
        name: "goal",
        type: "select",
        options: [
          { value: "0.8", label: "health.protein.maintenance" },
          { value: "1.9", label: "health.protein.muscle" },
          { value: "1.4", label: "health.protein.loss" },
        ],
      },
    ],
    formulaId: "protein",
    sections: [
      { id: "intro", titleKey: "health.protein.about", contentKey: "health.protein.aboutText" },
      { id: "formula", titleKey: "health.protein.formula", contentKey: "health.protein.formulaText" },
    ],
    faqTitleKey: "health.protein.faqTitle",
    faqs: [
      { qKey: "health.protein.faq.0.q", aKey: "health.protein.faq.0.a" },
      { qKey: "health.protein.faq.1.q", aKey: "health.protein.faq.1.a" },
      { qKey: "health.protein.faq.2.q", aKey: "health.protein.faq.2.a" },
      { qKey: "health.protein.faq.3.q", aKey: "health.protein.faq.3.a" },
      { qKey: "health.protein.faq.4.q", aKey: "health.protein.faq.4.a" },
      { qKey: "health.protein.faq.5.q", aKey: "health.protein.faq.5.a" },
    ],
  },
  {
    slug: "tdee-calculator",
    metaTitleKey: "health.tdee.metaTitle",
    metaDescriptionKey: "health.tdee.metaDescription",
    titleKey: "health.tdee.title",
    category: "Health",
    descriptionKey: "health.tdee.desc",
    inputs: [
      { label: "health.tdee.age", name: "age", type: "number", unit: "years" },
      { label: "health.tdee.weight", name: "weight", type: "number", unit: "kg" },
      { label: "health.tdee.height", name: "height", type: "number", unit: "cm" },
      {
        label: "health.tdee.activity",
        name: "activity",
        type: "select",
        options: [
          { value: "1.2", label: "health.tdee.sedentary" },
          { value: "1.375", label: "health.tdee.light" },
          { value: "1.55", label: "health.tdee.moderate" },
          { value: "1.725", label: "health.tdee.active" },
        ],
      },
    ],
    formulaId: "tdee",
    sections: [
      { id: "intro", titleKey: "health.tdee.about", contentKey: "health.tdee.aboutText" },
      { id: "formula", titleKey: "health.tdee.formula", contentKey: "health.tdee.formulaText" },
    ],
    faqTitleKey: "health.tdee.faqTitle",
    faqs: [
      { qKey: "health.tdee.faq.0.q", aKey: "health.tdee.faq.0.a" },
      { qKey: "health.tdee.faq.1.q", aKey: "health.tdee.faq.1.a" },
      { qKey: "health.tdee.faq.2.q", aKey: "health.tdee.faq.2.a" },
      { qKey: "health.tdee.faq.3.q", aKey: "health.tdee.faq.3.a" },
      { qKey: "health.tdee.faq.4.q", aKey: "health.tdee.faq.4.a" },
      { qKey: "health.tdee.faq.5.q", aKey: "health.tdee.faq.5.a" },
    ],
  },
  {
    slug: "macro-calculator",
    metaTitleKey: "health.macros.metaTitle",
    metaDescriptionKey: "health.macros.metaDescription",
    titleKey: "health.macros.title",
    category: "Health",
    descriptionKey: "health.macros.desc",
    inputs: [
      { label: "health.macros.calories", name: "calories", type: "number", unit: "kcal" },
      {
        label: "health.macros.diet",
        name: "diet",
        type: "select",
        options: [
          { value: "balanced", label: "health.macros.balanced" },
          { value: "lowcarb", label: "health.macros.lowCarb" },
          { value: "highprotein", label: "health.macros.highProtein" },
        ],
      },
    ],
    formulaId: "macros",
    sections: [
      { id: "intro", titleKey: "health.macros.about", contentKey: "health.macros.aboutText" },
      { id: "formula", titleKey: "health.macros.formula", contentKey: "health.macros.formulaText" },
    ],
    faqTitleKey: "health.macros.faqTitle",
    faqs: [
      { qKey: "health.macros.faq.0.q", aKey: "health.macros.faq.0.a" },
      { qKey: "health.macros.faq.1.q", aKey: "health.macros.faq.1.a" },
      { qKey: "health.macros.faq.2.q", aKey: "health.macros.faq.2.a" },
      { qKey: "health.macros.faq.3.q", aKey: "health.macros.faq.3.a" },
      { qKey: "health.macros.faq.4.q", aKey: "health.macros.faq.4.a" },
      { qKey: "health.macros.faq.5.q", aKey: "health.macros.faq.5.a" },
    ],
  },
  {
    slug: "body-fat-percentage",
    metaTitleKey: "health.bfp.metaTitle",
    metaDescriptionKey: "health.bfp.metaDescription",
    titleKey: "health.bfp.title",
    category: "Health",
    descriptionKey: "health.bfp.desc",
    inputs: [
      { label: "health.bfp.waist", name: "waist", type: "number", unit: "cm" },
      { label: "health.bfp.hip", name: "hip", type: "number", unit: "cm" },
      { label: "health.bfp.neck", name: "neck", type: "number", unit: "cm" },
    ],
    formulaId: "bfp",
    sections: [
      { id: "intro", titleKey: "health.bfp.about", contentKey: "health.bfp.aboutText" },
      { id: "formula", titleKey: "health.bfp.formula", contentKey: "health.bfp.formulaText" },
    ],
    faqTitleKey: "health.bfp.faqTitle",
    faqs: [
      { qKey: "health.bfp.faq.0.q", aKey: "health.bfp.faq.0.a" },
      { qKey: "health.bfp.faq.1.q", aKey: "health.bfp.faq.1.a" },
      { qKey: "health.bfp.faq.2.q", aKey: "health.bfp.faq.2.a" },
      { qKey: "health.bfp.faq.3.q", aKey: "health.bfp.faq.3.a" },
      { qKey: "health.bfp.faq.4.q", aKey: "health.bfp.faq.4.a" },
      { qKey: "health.bfp.faq.5.q", aKey: "health.bfp.faq.5.a" },
    ],
  },
]